# Generated by Django 3.2.20 on 2025-06-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_mov', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('secao', models.CharField(blank=True, max_length=255, null=True)),
                ('subclasse', models.CharField(blank=True, max_length=255, null=True)),
                ('saldo_movimentacao', models.BigIntegerField(blank=True, null=True)),
                ('cbo_2002_ocupacao', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('grau_de_instrucao', models.CharField(blank=True, max_length=255, null=True)),
                ('idade', models.FloatField(blank=True, null=True)),
                ('horas_contratuais', models.FloatField(blank=True, null=True)),
                ('raca_cor', models.CharField(blank=True, max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_empregador', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_estabelecimento', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_movimentacao', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_de_deficiencia', models.CharField(blank=True, max_length=255, null=True)),
                ('ind_trab_intermitente', models.CharField(blank=True, max_length=255, null=True)),
                ('ind_trab_parcial', models.CharField(blank=True, max_length=255, null=True)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('tam_estab_jan', models.CharField(blank=True, max_length=255, null=True)),
                ('indicador_aprendiz', models.CharField(blank=True, max_length=255, null=True)),
                ('origem_da_informacao', models.CharField(blank=True, max_length=255, null=True)),
                ('indicador_de_fora_do_prazo', models.CharField(blank=True, max_length=255, null=True)),
                ('unidade_salario_codigo', models.BigIntegerField(blank=True, null=True)),
                ('faixa_etaria', models.CharField(blank=True, max_length=255, null=True)),
                ('faixa_hora_contrat', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
