# Generated by Django 3.2.20 on 2025-12-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
