# Generated by Django 3.2.20 on 2025-12-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movimentacao_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='CagedEst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=500, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=500, null=True)),
                ('municipio', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=500, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('cnae_2_0_classe', models.CharField(blank=True, max_length=10, null=True)),
                ('cnae_2_0_subclasse', models.CharField(blank=True, max_length=10, null=True)),
                ('secao', models.CharField(blank=True, max_length=255, null=True)),
                ('porte', models.CharField(blank=True, max_length=100, null=True)),
                ('natureza_juridica', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_estabelecimento', models.CharField(blank=True, max_length=100, null=True)),
                ('competencia', models.CharField(blank=True, max_length=10, null=True)),
                ('ano', models.IntegerField(blank=True, db_index=True, null=True)),
                ('admissoes', models.IntegerField(blank=True, default=0, null=True)),
                ('desligamentos', models.IntegerField(blank=True, default=0, null=True)),
                ('saldo', models.IntegerField(blank=True, null=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CAGED Estabelecimento',
                'verbose_name_plural': 'CAGED Estabelecimentos',
                'db_table': 'core_cagedest',
                'ordering': ['-ano', 'municipio'],
            },
        ),
        migrations.AddIndex(
            model_name='cagedest',
            index=models.Index(fields=['cnpj', 'ano'], name='core_cagede_cnpj_e8144f_idx'),
        ),
        migrations.AddIndex(
            model_name='cagedest',
            index=models.Index(fields=['municipio', 'ano'], name='core_cagede_municip_97c1e3_idx'),
        ),
    ]
