# Generated by Django 3.2.20 on 2025-12-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20251207_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoArapiraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(db_index=True, help_text='Ex: jan a dez 2018, 2017, série 2002 A 2019', max_length=100, unique=True)),
                ('ano_referencia', models.IntegerField(db_index=True, help_text='Ano principal do período')),
                ('ano_2002', models.IntegerField(blank=True, null=True)),
                ('ano_2003', models.IntegerField(blank=True, null=True)),
                ('ano_2004', models.IntegerField(blank=True, null=True)),
                ('ano_2005', models.IntegerField(blank=True, null=True)),
                ('ano_2006', models.IntegerField(blank=True, null=True)),
                ('ano_2007', models.IntegerField(blank=True, null=True)),
                ('ano_2008', models.IntegerField(blank=True, null=True)),
                ('ano_2009', models.IntegerField(blank=True, null=True)),
                ('ano_2010', models.IntegerField(blank=True, null=True)),
                ('ano_2011', models.IntegerField(blank=True, null=True)),
                ('ano_2012', models.IntegerField(blank=True, null=True)),
                ('ano_2013', models.IntegerField(blank=True, null=True)),
                ('ano_2014', models.IntegerField(blank=True, null=True)),
                ('ano_2015', models.IntegerField(blank=True, null=True)),
                ('ano_2016', models.IntegerField(blank=True, null=True)),
                ('ano_2017', models.IntegerField(blank=True, null=True)),
                ('ano_2018', models.IntegerField(blank=True, null=True)),
                ('ano_2019', models.IntegerField(blank=True, null=True)),
                ('sheet_origem', models.CharField(max_length=100)),
                ('tipo_periodo', models.CharField(help_text='serie_historica, mensal, anual', max_length=50)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Saldo de Emprego - Arapiraca',
                'verbose_name_plural': 'Saldos de Emprego - Arapiraca',
                'db_table': 'core_saldo_arapiraca',
                'ordering': ['-ano_referencia', 'periodo'],
            },
        ),
    ]
