from decouple import config
import os

GOOGLE_APPLICATION_CREDENTIALS = config("GOOGLE_APPLICATION_CREDENTIALS")
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = GOOGLE_APPLICATION_CREDENTIALS

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="*").split(',')