# Generated by Django 6.0.3 on 2026-03-31 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referenciais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_mov', models.IntegerField(blank=True, null=True)),
                ('competencia_dec', models.IntegerField(blank=True, null=True)),
                ('competencia_exc', models.IntegerField(blank=True, null=True)),
                ('idade', models.IntegerField(blank=True, db_column='idade', null=True)),
                ('valor_salario_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('horas_contratuais', models.IntegerField(blank=True, null=True)),
                ('saldo_movimentacao', models.IntegerField(blank=True, help_text='Saldo da movimentação: 1 (admissão) ou -1 (desligamento)', null=True)),
                ('salario', models.DecimalField(blank=True, db_column='salario', decimal_places=2, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.categoriareferencia')),
                ('cbo2002_ocupacao', models.ForeignKey(blank=True, db_column='cbo2002_ocupacao_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.cbo2002ocupacaoreferencia')),
                ('grau_instrucao', models.ForeignKey(blank=True, db_column='grau_instrucao_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.graudeinstrucaoreferencia')),
                ('ind_trab_intermitente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.indtrabintermitentereferencia')),
                ('ind_trab_parcial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.indtrabparcialreferencia')),
                ('indicador_aprendiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.indicadoraprendizreferencia')),
                ('indicador_exclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.indicadordeexclusãoreferencia')),
                ('indicador_fora_prazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.indicadordeforadoprazoreferencia')),
                ('municipio', models.ForeignKey(blank=True, db_column='municipio_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.municipioreferencia')),
                ('origem_informacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.origemdainformacaoreferencia')),
                ('raca_cor', models.ForeignKey(blank=True, db_column='raca_cor_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.racacorreferencia')),
                ('regiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.regiaoreferencia')),
                ('secao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.secaoreferencia')),
                ('sexo', models.ForeignKey(blank=True, db_column='sexo_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.sexoreferencia')),
                ('subclasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.subclassereferencia')),
                ('tam_estab_jan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.tamestabjanreferencia')),
                ('tipo_deficiencia', models.ForeignKey(blank=True, db_column='tipo_deficiencia_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.tipodeficienciareferencia')),
                ('tipo_empregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.tipoempregadorreferencia')),
                ('tipo_estabelecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.tipoestabelecimentoreferencia')),
                ('tipo_movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.tipomovimentacaoreferencia')),
                ('uf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.ufreferencia')),
                ('unidade_salario_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.unidadesalariocodigoreferencia')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'db_table': 'movimentacoes',
                'indexes': [models.Index(fields=['competencia_mov', 'municipio'], name='movimentaco_compete_cf05d1_idx'), models.Index(fields=['subclasse'], name='idx_subclasse'), models.Index(fields=['cbo2002_ocupacao'], name='movimentaco_cbo2002_bc5596_idx'), models.Index(fields=['saldo_movimentacao'], name='movimentaco_saldo_m_7675ac_idx')],
            },
        ),
    ]
