# Generated by Django 5.1.5 on 2026-03-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referenciais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                ('competencia_movimentacao', models.IntegerField(blank=True, db_column='competencia_mov', null=True)),
               
                ('idade', models.IntegerField(blank=True, db_column='idade', null=True)),
                ('salario', models.DecimalField(blank=True, db_column='salario', decimal_places=2, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cbo2002_ocupacao', models.ForeignKey(blank=True, db_column='cbo2002_ocupacao_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='referenciais.cbo2002ocupacaoreferencia')),
                ('grau_instrucao', models.ForeignKey(blank=True, db_column='grau_instrucao_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='referenciais.graudeinstrucaoreferencia')),
                ('municipio', models.ForeignKey(blank=True, db_column='municipio_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='referenciais.municipioreferencia')),
                ('raca_cor', models.ForeignKey(blank=True, db_column='raca_cor_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='referenciais.racacorreferencia')),
                ('sexo', models.ForeignKey(blank=True, db_column='sexo_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='referenciais.sexoreferencia')),
                ('tipo_deficiencia', models.ForeignKey(blank=True, db_column='tipo_deficiencia_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='referenciais.tipodeficienciareferencia')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'db_table': 'movimentacoes',
                'indexes': [models.Index(fields=['competencia_movimentacao', 'municipio'], name='movimentaco_compete_cf05d1_idx'), models.Index(fields=['cbo2002_ocupacao'], name='movimentaco_cbo2002_bc5596_idx')],
            },
        ),
    ]
