# Generated by Django 6.0.3 on 2026-04-09 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
        ('referenciais', '0002_faixaetariaraisreferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='ind_trab_parcial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referenciais.indtrabparcialreferencia'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='salario',
            field=models.DecimalField(blank=True, db_column='salario', decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
