# Generated by Django 5.1.5 on 2026-03-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
         migrations.RunSQL(
            sql="""
                -- Remover colunas de relacionamento (ForeignKey)
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS regiao_id CASCADE;
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS uf_id CASCADE;
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS secao_id CASCADE;
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS subclasse_id CASCADE;
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS categoria_id CASCADE;
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS tipo_empregador_id CASCADE;
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS tipo_estabelecimento_id CASCADE;
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS tipo_movimentacao_id CASCADE;
                
                -- Remover colunas numéricas
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS horas_contratuais CASCADE;
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS tamanho_estabelecimento CASCADE;
                
                -- Remover colunas de texto/indicadores
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS indicador_trabalho_intermitente CASCADE;
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS indicador_trabalho_parcial CASCADE;
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS indicador_aprendiz CASCADE;
                ALTER TABLE movimentacoes DROP COLUMN IF EXISTS origem_informacao CASCADE;
                
                -- Remover índices relacionados (se existirem)
                DROP INDEX IF EXISTS idx_subclasse;
                DROP INDEX IF EXISTS movimentacoes_tipo_empregador_id_idx;
                DROP INDEX IF EXISTS movimentacoes_tipo_estabelecimento_id_idx;
                DROP INDEX IF EXISTS movimentacoes_tipo_movimentacao_id_idx;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
