# Generated by Django 5.1.5 on 2026-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_remove_unused_columns'),
        ('referenciais', '0004_remove_django_auth_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='saldo_movimentacao',
            field=models.IntegerField(blank=True, help_text='Saldo da movimentação: 1 (admissão) ou -1 (desligamento)', null=True),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['saldo_movimentacao'], name='movimentaco_saldo_m_7675ac_idx'),
        ),
    ]
