# Generated by Django 6.0.3 on 2026-04-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoRais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairros_sp', models.CharField(blank=True, max_length=50, null=True)),
                ('bairros_fortaleza', models.CharField(blank=True, max_length=50, null=True)),
                ('bairros_rj', models.CharField(blank=True, max_length=50, null=True)),
                ('distritos_sp', models.CharField(blank=True, max_length=50, null=True)),
                ('regioes_adm_df', models.IntegerField(null=True)),
                ('mun_trab', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('municipio', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('cbo_ocupacao_2002', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('cnae_2_0_classe', models.CharField(max_length=15, null=True)),
                ('cnae_95_classe', models.CharField(max_length=15, null=True)),
                ('cnae_2_0_subclasse', models.CharField(max_length=15, null=True)),
                ('ibge_subsetor', models.IntegerField(null=True)),
                ('natureza_juridica', models.CharField(max_length=10, null=True)),
                ('idade', models.IntegerField(null=True)),
                ('faixa_etaria', models.IntegerField(null=True)),
                ('sexo_trabalhador', models.IntegerField(null=True)),
                ('raca_cor', models.IntegerField(null=True)),
                ('escolaridade_apos_2005', models.IntegerField(null=True)),
                ('nacionalidade', models.IntegerField(null=True)),
                ('ind_portador_defic', models.IntegerField(null=True)),
                ('tipo_defic', models.IntegerField(null=True)),
                ('ano_chegada_brasil', models.IntegerField(null=True)),
                ('vinculo_ativo_31_12', models.IntegerField(null=True)),
                ('faixa_hora_contrat', models.IntegerField(null=True)),
                ('qtd_hora_contr', models.IntegerField(null=True)),
                ('faixa_tempo_emprego', models.IntegerField(null=True)),
                ('tempo_emprego', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('tipo_admissao', models.IntegerField(null=True)),
                ('tipo_estab', models.IntegerField(null=True)),
                ('tipo_estab_1', models.CharField(max_length=20, null=True)),
                ('tipo_vinculo', models.IntegerField(null=True)),
                ('tamanho_estabelecimento', models.IntegerField(null=True)),
                ('ind_cei_vinculado', models.IntegerField(null=True)),
                ('ind_simples', models.IntegerField(null=True)),
                ('ind_trab_intermitente', models.IntegerField(null=True)),
                ('ind_trab_parcial', models.IntegerField(null=True)),
                ('causa_afastamento_1', models.IntegerField(null=True)),
                ('causa_afastamento_2', models.IntegerField(null=True)),
                ('causa_afastamento_3', models.IntegerField(null=True)),
                ('motivo_desligamento', models.IntegerField(null=True)),
                ('mes_admissao', models.IntegerField(null=True)),
                ('mes_desligamento', models.CharField(max_length=10, null=True)),
                ('qtd_dias_afastamento', models.IntegerField(null=True)),
                ('vl_remun_dezembro_nom', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vl_remun_dezembro_sm', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vl_remun_media_nom', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vl_remun_media_sm', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('faixa_remun_dezem_sm', models.IntegerField(null=True)),
                ('faixa_remun_media_sm', models.IntegerField(null=True)),
                ('vl_rem_janeiro_sc', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vl_rem_fevereiro_sc', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vl_rem_marco_sc', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vl_rem_abril_sc', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vl_rem_maio_sc', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vl_rem_junho_sc', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vl_rem_julho_sc', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vl_rem_agosto_sc', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vl_rem_setembro_sc', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vl_rem_outubro_sc', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vl_rem_novembro_sc', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('ano_base', models.IntegerField(db_index=True)),
            ],
            options={
                'db_table': 'movimentacoes_rais',
            },
        ),
    ]
