# Generated by Django 6.0.1 on 2026-01-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cbo2002ocupacaoReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenciaBaseInterger',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GraudeinstrucaoReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicadorAprendizReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicadorDeExclusãoReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicadorDeForaDoPrazoReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndTrabInparcialReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndTrabIntermitenteReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MunicipioReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrigemDaInformacaoReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RacaCorReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegiaoReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecaoReferencia',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SexoReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubclasseReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TamEstabJanReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDeficienciaReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmpregadorReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEstabelecimentoReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMovimentacaoReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UfReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeSalarioCodigoReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetenciaMovReferencia',
            fields=[
                ('referenciabaseinterger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='referenciais.referenciabaseinterger')),
            ],
            bases=('referenciais.referenciabaseinterger',),
        ),
        migrations.CreateModel(
            name='CompetênciaDecReferencia',
            fields=[
                ('referenciabaseinterger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='referenciais.referenciabaseinterger')),
            ],
            bases=('referenciais.referenciabaseinterger',),
        ),
        migrations.CreateModel(
            name='CompetênciaExcReferencia',
            fields=[
                ('referenciabaseinterger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='referenciais.referenciabaseinterger')),
            ],
            bases=('referenciais.referenciabaseinterger',),
        ),
        migrations.CreateModel(
            name='HorasContratuaisReferencia',
            fields=[
                ('referenciabaseinterger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='referenciais.referenciabaseinterger')),
            ],
            bases=('referenciais.referenciabaseinterger',),
        ),
        migrations.CreateModel(
            name='IdadeReferencia',
            fields=[
                ('referenciabaseinterger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='referenciais.referenciabaseinterger')),
            ],
            bases=('referenciais.referenciabaseinterger',),
        ),
        migrations.CreateModel(
            name='SalarioReferencia',
            fields=[
                ('referenciabaseinterger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='referenciais.referenciabaseinterger')),
            ],
            bases=('referenciais.referenciabaseinterger',),
        ),
        migrations.CreateModel(
            name='SaldoMovimentacaoReferencia',
            fields=[
                ('referenciabaseinterger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='referenciais.referenciabaseinterger')),
            ],
            bases=('referenciais.referenciabaseinterger',),
        ),
        migrations.CreateModel(
            name='ValorSalarioFixoReferencia',
            fields=[
                ('referenciabaseinterger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='referenciais.referenciabaseinterger')),
            ],
            bases=('referenciais.referenciabaseinterger',),
        ),
    ]
