# Generated by Django 5.1.5 on 2026-03-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referenciais', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                -- Remover tabelas de referência não utilizadas
                DROP TABLE IF EXISTS referenciais_competenciamov_referencia CASCADE;
                DROP TABLE IF EXISTS referenciais_regiaoreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_ufreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_secaoreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_subclassereferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_categoriareferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_horascontratuaisreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_tipoempregadorreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_tipoestabelecimentoreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_tipomovimentacaoreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_indtrabintermitentereferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_indtrabparcialreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_tamestabjanreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_indicadoraprendizreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_origemdainformacaoreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_competenciadecreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_competenciaexcreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_indicadordeexclusaoreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_indicadordeforadoprazoreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_unidadesalariocodigoreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_valorsalariofixoreferencia CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
