# Generated by Django 6.0.1 on 2026-01-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referenciais', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndTrabInparcialReferencia',
            new_name='IndTrabParcialReferencia',
        ),
    ]
