# Generated by Django 6.0.3 on 2026-04-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referenciais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaEtariaRaisReferencia',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Faixa Etária RAIS',
                'verbose_name_plural': 'Faixas Etárias RAIS',
            },
        ),
    ]
