# Generated by Django 6.0.3 on 2026-04-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referenciais', '0002_faixaetariaraisreferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrauDeInstrucaoRaisReferencia',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
