# Generated by Django 5.1.5 on 2026-03-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referenciais', '0002_remove_unused_reference_tables'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                -- Remover tabelas com nomes acentuados (usar aspas duplas)
                DROP TABLE IF EXISTS "referenciais_competênciadecreferencia" CASCADE;
                DROP TABLE IF EXISTS "referenciais_competênciaexcreferencia" CASCADE;
                DROP TABLE IF EXISTS "referenciais_indicadordeexclusãoreferencia" CASCADE;
                DROP TABLE IF EXISTS "referenciais_saldomovimentacaoreferencia" CASCADE;
                
                -- Remover classes base se existirem
                DROP TABLE IF EXISTS referenciais_referenciabaseinterger CASCADE;
                DROP TABLE IF EXISTS referenciais_referenciabase CASCADE;
                DROP TABLE IF EXISTS referenciais_idadereferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_salarioreferencia CASCADE;
                DROP TABLE IF EXISTS referenciais_competenciamovreferencia CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
