# Generated by Django 6.0.3 on 2026-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referenciais', '0003_graudeinstrucaoraisreferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graudeinstrucaoraisreferencia',
            name='codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='graudeinstrucaoraisreferencia',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
