# Generated by Django 5.1.5 on 2026-03-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referenciais', '0003_remove_remaining_unused_tables'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                -- Remover tabelas de autenticação (backup já feito!)
                DROP TABLE IF EXISTS auth_user_groups CASCADE;
                DROP TABLE IF EXISTS auth_user_user_permissions CASCADE;
                DROP TABLE IF EXISTS auth_group_permissions CASCADE;
                DROP TABLE IF EXISTS auth_permission CASCADE;
                DROP TABLE IF EXISTS auth_group CASCADE;
                DROP TABLE IF EXISTS auth_user CASCADE;
                
                -- Remover tabelas de admin e sessão
                DROP TABLE IF EXISTS django_admin_log CASCADE;
                DROP TABLE IF EXISTS django_session CASCADE;
                DROP TABLE IF EXISTS django_content_type CASCADE;
                
                -- MANTER django_migrations (necessária para controle de migrations)
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
