# Generated by Django 5.1.5 on 2026-03-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referenciais', '0004_remove_django_auth_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarioBaseReferencia',
            fields=[
                ('desde', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('legislacao', models.CharField(max_length=255)),
                ('rejuste', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
